# Generated by Django 4.2 on 2024-06-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="modify_number",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
