# Generated by Django 4.2 on 2024-06-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0002_question_modify_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="visited_number",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
